#########################################################################
# Title:            Community: Daily Notes                              #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  m0ngr31/dailynotes                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: dailynotes
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: dailynotes
    state: absent

- name: Create dailynotes directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/dailynotes

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/dailynotes:/app/config"

- name: Create and start container
  docker_container:
    name: dailynotes
    image: m0ngr31/dailynotes
    pull: yes
    exposed_ports:
      - "5000"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "002"
      VIRTUAL_HOST: "dailynotes.{{ user.domain }}"
      VIRTUAL_PORT: "5000"
      LETSENCRYPT_HOST: "dailynotes.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - dailynotes
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
