#########################################################################
# Title:            Community: Readarr                                  #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  lscr.io/linuxserver/emulatorjs:latest               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: emulatorjs
  when: cloudflare_enabled

- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: emulatorjsadmin
  when: cloudflare_enabled
  
- name: Stop and remove any existing container
  docker_container:
    name: emulatorjs
    state: absent

- name: Create emulatorjs directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/emulatorjs

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/emulatorjs:/config"
      - "/mnt/unionfs/Media/Roms:/data"


- name: Create and start container
  docker_container:
    name: emulatorjs
    image: lscr.io/linuxserver/emulatorjs:latest
    pull: yes
    exposed_ports:
      - 80
      - 3000
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "002"
      VIRTUAL_HOST: "emulatorjs.{{ user.domain }},emulatorjsadmin.{{ user.domain }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "emulatorjs.{{ user.domain }},emulatorjsadmin.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - emulatorjs
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
