#########################################################################
# Title:            Community: Readarr                                  #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  lscr.io/linuxserver/webtop                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: webtop
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: webtop
    state: absent

- name: Create webtop directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/webtop

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/webtop:/config"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/host"


- name: Create and start container
  docker_container:
    name: webtop
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    pull: yes
    exposed_ports:
      - "3000"
    security_opts:
      - seccomp:unconfined
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "002"
      VIRTUAL_HOST: "webtop.{{ user.domain }}"
      VIRTUAL_PORT: "3000"
      LETSENCRYPT_HOST: "webtop.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      KEYBOARD: "en-us-qwerty"
      TITLE: "Webtop"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "com.centurylinklabs.watchtower.enable": "false"
    networks:
      - name: cloudbox
        aliases:
          - webtop
    privileged: yes
    shm_size: "1GB"
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
