#########################################################################
# Title:            Community: Readarr                                  #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  housewrecker/gaps:latest                            #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: namer
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: namer
    state: absent

- name: Create namer directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/namer
    - /mnt/local/downloads/namer
    - /mnt/local/downloads/namer/watch

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/namer:/config"
      - "/mnt/local/downloads/namer:/data"

- name: Create and start container
  docker_container:
    name: namer
    image: ghcr.io/theporndatabase/namer:latest
    pull: yes
    exposed_ports:
      - "6980"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "002"
      VIRTUAL_HOST: "namer.{{ user.domain }}"
      VIRTUAL_PORT: "6980"
      LETSENCRYPT_HOST: "namer.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
      NAMER_CONFIG: "/config/namer.cfg"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - namer
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
