#########################################################################
# Title:            Community: Jellyfin-Autoscan                        #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  ghcr.io/niniyas/autoscan:beta_amd64                 #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- name: Stop and remove any existing container
  docker_container:
    name: jellyfin_autoscan
    state: absent

- name: Create jellyfin_autoscan directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/jellyfin_autoscan

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/jellyfin_autoscan:/config"
      - "/opt/plex:/opt/plex"
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt:/mnt"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases:/plexDb"

- name: Create and start container
  docker_container:
    name: jellyfin_autoscan
    image: ghcr.io/niniyas/autoscan:beta_amd64
    pull: yes
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - jellyfin_autoscan
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
