#########################################################################
# Title:            Community: QbittorrentVPNX                          #
# Author(s):        Kalroth, Migz93                                     #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  dyonr/qbittorrentvpn                                #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Gather list of QbittorrentVPNX Docker containers"
  shell: "docker ps -a --format '{{ '{{' }} .Names{{ '}}' }}' --filter label=com.github.cloudbox.community=qbittorrentvpnx | xargs echo -n"
  register: cloudbox_community_qbittorrentvpnx
  ignore_errors: yes

- name: "Stop all QbittorrentVPNX Docker containers"
  shell: "docker stop {{ cloudbox_community_qbittorrentvpnx.stdout }}"
  ignore_errors: yes
  when: (cloudbox_community_qbittorrentvpnx.stdout | trim | length > 0)

- name: "Remove all QbittorrentVPNX Docker containers"
  shell: "docker rm {{ cloudbox_community_qbittorrentvpnx.stdout }}"
  ignore_errors: yes
  when: (cloudbox_community_qbittorrentvpnx.stdout | trim | length > 0)


- name: "Execute QbittorrentVPNX roles"
  include_tasks: template.yml
  vars:
    rolename: "{{ role }}"
  with_items: "{{ qbittorrentvpnx.roles }}"
  loop_control:
    loop_var: role
