#########################################################################
# Title:            Community: QbittorrentVPNX Tempate                  #
# Author(s):        Kalroth, Migz93                                     #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  dyonr/qbittorrentvpn                                #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Install named qbittorrentvpn role"
  debug:
    msg: "Installing {{ rolename }} qbittorrentvpn role"

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: "qbittorrentvpn{{ rolename }}"
  when: cloudflare_enabled

- name: Create qbittorrentvpn directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - "/opt/qbittorrentvpn{{ rolename }}"
    - "/mnt/local/downloads/torrents/qbittorrentvpn{{ rolename }}"
    - "/mnt/local/downloads/torrents/qbittorrentvpn{{ rolename }}/completed"
    - "/mnt/local/downloads/torrents/qbittorrentvpn{{ rolename }}/incomplete"

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/qbittorrentvpn{{ rolename }}:/config"
      - "/mnt/local/downloads/torrents/qbittorrentvpn{{ rolename }}:/downloads/torrents/qbittorrentvpn{{ rolename }}"

- name: Create and start container
  docker_container:
    name: "qbittorrentvpn{{ rolename }}"
    image: "dyonr/qbittorrentvpn"
    pull: yes
    exposed_ports:
      - "8080"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VPN_TYPE: "openvpn"
      VPN_ENABLED: "yes"
      VPN_USERNAME: "{{ qbittorrentvpnx.vpn_user|default('username',true) }}"
      VPN_PASSWORD: "{{ qbittorrentvpnx.vpn_pass|default('password',true) }}"
      LAN_NETWORK: "192.168.0.0/24"
      INSTALL_PYTHON3: "yes"
      VIRTUAL_HOST: "qbittorrentvpn{{ rolename }}.{{ user.domain }}"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "qbittorrentvpn{{ rolename }}.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "com.github.cloudbox.community": "qbittorrentvpnx"
    networks:
      - name: cloudbox
        aliases:
          - "qbittorrentvpn{{ rolename }}"
    purge_networks: yes
    privileged: true
    restart_policy: unless-stopped
    state: started
