#########################################################################
# Title:            Community: Grocy                                  #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  lscr.io/linuxserver/grocy:latest                            #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: grocy
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: grocy
    state: absent

- name: Create grocy directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/grocy

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/grocy:/config"

- name: Create and start container
  docker_container:
    name: grocy
    image: lscr.io/linuxserver/grocy:latest
    pull: yes
    exposed_ports:
      - "80"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "002"
      VIRTUAL_HOST: "grocy.{{ user.domain }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "grocy.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - grocy
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
