#########################################################################
# Title:            Community: Metube                                   #
# Author(s):        halfdeadgames                                       #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  alexta69/metube                                     #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: metube
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: metube
    state: absent

- name: Create metube directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/metube
    - /mnt/local/downloads/metube

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/metube:/config"
      - "/mnt/local/downloads/metube:/downloads"

- name: Create and start container
  docker_container:
    name: metube
    image: alexta69/metube
    pull: yes
    exposed_ports:
      - "8081"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: "002"
      VIRTUAL_HOST: "metube.{{ user.domain }}"
      VIRTUAL_PORT: "8081"
      LETSENCRYPT_HOST: "metube.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
      STATE_DIR: "/config"
    volumes: "{{ default_volumes }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - metube
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
